# -*- encoding: utf-8 -*-
# stub: regtest 0.5.0 ruby lib
#
# This file is automatic generated by rim.
# PLEASE DO NOT EDIT IT DIRECTLY!
# Change instead the values in Rim.setup in Rakefile.

Gem::Specification.new do |s|
  s.name = "regtest"
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jan Friedrich"]
  s.date = "2015-10-13"
  s.description = "Regression testing in Ruby."
  s.email = "janfri26@gmail.com"
  s.files = ["Changelog", "README.md", "Rakefile", "lib/regtest", "lib/regtest.rb", "lib/regtest/task.rb"]
  s.homepage = "http://gitorious.org/regtest"
  s.licenses = ["Ruby"]
  s.rubygems_version = "2.5.0"
  s.summary = "Regression testing in Ruby."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rim>, ["~> 2.6"])
    else
      s.add_dependency(%q<rim>, ["~> 2.6"])
    end
  else
    s.add_dependency(%q<rim>, ["~> 2.6"])
  end
end
