name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - ruby-head
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install Dependencies
        run: |
          gem install rim
      - name: Generate .regtestrc
        run: |
          echo "require 'regtest/git'" > .regtestrc
      - name: Run Tests
        run: |
          ruby -I lib regtest/combinations.rb regtest/examples.rb regtest/filename\ with\ spaces.rb regtest/log.rb regtest/log_append.rb regtest/log_rewrite.rb regtest/metatest.rb regtest/no_samples.rb regtest/toplevel.rb
